# Generated by Django 3.1.1 on 2020-09-05 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('access_token', models.CharField(default=uuid.uuid1, max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(verbose_name='deleted at')),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='hyp.customer'
                )),
            ],
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='finished',
            new_name='stopped',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='participant',
        ),
        migrations.AddField(
            model_name='interaction',
            name='experiment',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='hyp.experiment'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='participant_id',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
