# Generated by Django 3.1.4 on 2021-02-17 21:45

from django.db import migrations
from django.contrib.sites.models import Site


def update_site_name(apps, schema_editor):
    site = Site.objects.first()
    site.name = "Hyp"
    site.domain = "onhyp.com"
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0002_auto_20210211_2245'),
    ]

    operations = [
        migrations.RunPython(update_site_name)
    ]
