# Generated by Django 3.1.4 on 2021-02-17 21:45

from django.db import migrations


def update_site_name(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site = Site.objects.first()

    if site is None:
        Site.objects.create(domain="onhyp.com", name="Hyp")
    else:
        site.name = "Hyp"
        site.domain = "onhyp.com"
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0002_auto_20210211_2245'),
        ('sites', '0002_alter_domain_unique')
    ]

    operations = [
        migrations.RunPython(update_site_name)
    ]
