# Generated by Django 3.1.1 on 2020-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0002_auto_20200905_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='deleted at'),
        ),
    ]
