# Generated by Django 3.1.1 on 2020-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0003_auto_20200905_1859'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(
                fields=('experiment_id', 'participant_id'),
                name='uniq_interaction_per_experiment_and_participant'
            ),
        ),
    ]
