# Generated by Django 3.1.7 on 2021-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0003_auto_20210217_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='apikey',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deactivated at'),
        ),
        migrations.AddField(
            model_name='hypuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deactivated at'),
        ),
    ]
