# Generated by Django 3.1.7 on 2021-03-21 18:01

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group, Permission


def permissions_for_model(model):
    type = ContentType.objects.get_for_model(model)
    permissions = Permission.objects.filter(content_type=type)

    return permissions


def create_groups(apps, schema_editor):
    Experiment = apps.get_model('hyp', 'Experiment')
    HypUser = apps.get_model('hyp', 'HypUser')
    ApiKey = apps.get_model('hyp', 'ApiKey')
    Customer = apps.get_model('hyp', 'Customer')

    team_admins = Group(name="Team admins")
    team_admins.save()

    for model in [Experiment, HypUser, ApiKey, Customer]:
        permissions = permissions_for_model(model)

        for permission in permissions:
            team_admins.permissions.add(permission)

    experimentors = Group(name="Team experimentors")
    experimentors.save()

    permissions = permissions_for_model(Experiment)

    for permission in permissions:
        experimentors.permissions.add(permission)

    observers = Group(name="Team observers")
    observers.save()

    permission = Permission.objects.get(codename="view_experiment")
    observers.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0004_auto_20210321_0137'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
