# Generated by Django 3.1.7 on 2021-03-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0005_CreateGroups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='production',
        ),
    ]
