# Generated by Django 3.1.1 on 2020-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0005_auto_20201125_1524'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(
                fields=('experiment_id', 'name'),
                name='uniq_variant_name_per_experiment'
            ),
        ),
    ]
