# Generated by Django 3.1.1 on 2020-12-08 16:11

from django.db import migrations, models
import hyp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0006_auto_20201125_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='access_token',
            field=models.CharField(default=hyp.models.create_access_token, max_length=200),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used at'),
        ),
    ]
