# Generated by Django 3.1.7 on 2021-03-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0006_auto_20210321_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hyp.customer'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(fields=('customer_id', 'deactivated_at'), name='uniq_active_key_per_customer'),
        ),
    ]
