# Generated by Django 3.1.7 on 2021-03-21 21:49

from django.db import migrations


def insert_customers(apps, schema_editor):
    Experiment = apps.get_model('hyp', 'Experiment')

    experiments = Experiment.objects.all()
    for experiment in experiments:
        variants = experiment.variant_set.all()
        for variant in variants:
            variant.customer_id = experiment.customer_id
            variant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0007_auto_20210321_2147'),
    ]

    operations = [
        migrations.RunPython(insert_customers),
    ]
