# Generated by Django 3.1.7 on 2021-03-22 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0009_auto_20210321_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hyp.customer'),
        ),
    ]
