# Generated by Django 3.1.7 on 2021-03-22 00:54

from django.db import migrations


def insert_customers(apps, schema_editor):
    Experiment = apps.get_model('hyp', 'Experiment')

    experiments = Experiment.objects.all()
    for experiment in experiments:
        interactions = experiment.interaction_set.all()
        for interaction in interactions:
            interaction.customer_id = experiment.customer_id
            interaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0010_interaction_customer'),
    ]

    operations = [
        migrations.RunPython(insert_customers),
    ]
