# Generated by Django 3.1.7 on 2021-03-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0011_InsertInteractionCustomers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyp.customer'),
        ),
    ]
