# Generated by Django 3.1.7 on 2021-03-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0012_auto_20210322_0056'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apikey',
            name='uniq_active_key_per_customer',
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(deactivated_at=None), fields=('customer_id',), name='uniq_active_key_per_customer'),
        ),
    ]
