# Generated by Django 3.1.7 on 2021-03-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0013_auto_20210322_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
