# Generated by Django 3.1.7 on 2021-03-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0014_auto_20210329_0053'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer_id', 'experiment_id', 'participant_id', 'variant_id'], name='hyp_interac_custome_c6ff70_idx'),
        ),
    ]
