# Generated by Django 3.1.7 on 2021-03-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0015_auto_20210329_0105'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['access_token', 'deactivated_at', 'customer_id'], name='hyp_apikey_access__ec7e5c_idx'),
        ),
    ]
