# Generated by Django 3.1.7 on 2021-03-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0017_auto_20210329_0110'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='hyp_custome_name_be4c94_idx'),
        ),
    ]
