# Generated by Django 3.1.7 on 2021-04-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0019_auto_20210411_0219'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE FUNCTION maintain_counter_caches_trg() RETURNS TRIGGER AS
        $$
        BEGIN
          IF TG_OP IN ('UPDATE') THEN
            UPDATE hyp_variant SET num_conversions = num_conversions + 1 WHERE id = new.variant_id;
          END IF;
          IF TG_OP IN ('INSERT') THEN
            UPDATE hyp_variant SET num_interactions = num_interactions + 1 WHERE id = new.variant_id;
          END IF;
          RETURN NULL;
        END
        $$
        LANGUAGE plpgsql;

        CREATE TRIGGER maintain_interaction_counter_caches
        AFTER INSERT OR UPDATE OF converted ON hyp_interaction
        FOR EACH ROW
        EXECUTE PROCEDURE maintain_counter_caches_trg();
        """)
    ]
