# Generated by Django 3.1.7 on 2021-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0020_VariantCounterCacheTriggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
