# Generated by Django 3.1.7 on 2021-04-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0021_auto_20210411_2352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apikey',
            name='uniq_active_key_per_customer',
        ),
    ]
