# Generated by Django 3.2.5 on 2021-07-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0025_alter_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVariantMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('traffic_split', models.DecimalField(decimal_places=2, max_digits=4)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyp.experiment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyp.variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyvariantmetrics',
            index=models.Index(fields=['date', 'experiment_id'], name='hyp_dailyva_date_594e30_idx'),
        ),
    ]
