# Generated by Django 3.2.5 on 2021-07-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0026_auto_20210723_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvariantmetrics',
            name='date',
            field=models.DateField(),
        ),
    ]
