# Generated by Django 3.2.5 on 2021-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp', '0027_alter_dailyvariantmetrics_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyvariantmetrics',
            constraint=models.UniqueConstraint(fields=('date', 'variant_id'), name='uniq_metric_per_day_per_variant'),
        ),
    ]
