name: Code Quality

on:
  push:
    paths:
      - "**.py"

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: ./bin/flake8 --select=C,E,F,W,S,B,B9 --exclude=staticfiles,manage.py --ignore=S106 --max-line-length=100 web/web/**/*.py web/hyp/**/*.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
