name: Tests
on: [push]
jobs:
  build:
    name: UnitTest
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gethyped
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    # - name: Create database
    #   run: sudo createdb hyp2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        DB: postgres
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_PASSWORD: gethyped
      working-directory: ./web
      run: python manage.py test hyp/tests
